.\" Manpage for KANT.
.\" Contact bts@square-r00t.net to correct errors or typos.
.TH kant 1 "04 Sept 2017" "1.0" "KANT - Keysigning and Notification Tool"
.SH NAME
kant \- Sign GnuPG/OpenPGP/PGP keys and notify the key owner(s)
.SH SYNOPSIS
.HP \w'\fBgpasswd\fR\ 'u
\fBkant\fR [\fIoptions\fR] \fI\fR
.SH DESCRIPTION
.PP
Keysigning (and keysigning parties) are a lot of fun\&. Unfortunately, they can be intimidating to those new to the experience\&. This tool offers a simple and easy-to-use interface to sign public keys (normal, local-only, and/or non-exportable), set owner trust, specify level of checking done, and push the signatures to a keyserver\&. 
.SH OPTIONS
The nuseradd does not take any options. However, you can supply username.
.SH SEE ALSO
useradd(8), passwd(5), nuseradd.debian(8) 
.SH BUGS
No known bugs.
.SH AUTHOR
Brent Saner (bts@square-r00t.net)